name: Default MicroShift cluster

on:
  [workflow_dispatch, push]
jobs:
  microshift-cluster-demo:
    name: Default MicroShift cluster
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install sudo package
        if: env.ACT == 'true'
        run: apt update && apt install sudo gnupg -y
      - uses: ./
        name: "Create default MicroShift Cluster"
      - name: Cluster info
        run: |
          kubectl cluster-info 
